#!/bin/python3

import os

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    pDiagonal = 0
    sDiagonal = 0
    ptr = 0
    for x in range(len(arr)):
        pDiagonal += arr[x][ptr]
        ptr += 1
    ptr = (len(arr))-1
    for x in range(len(arr)):
        sDiagonal += arr[x][ptr]
        ptr -= 1
    return abs(pDiagonal-sDiagonal)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()