#!/bin/python3

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    pos = 0
    neg = 0
    z = 0
    for x in range(len(arr)):
        if (arr[x] == 0):
            z += 1
            continue
        elif (arr[x] > 0):
            pos += 1
        elif (arr[x] < 0):
            neg += 1
    print(pos/len(arr))
    print(neg/len(arr))
    print(z/len(arr))

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
