#!/bin/python3

#
# Complete the 'staircase' function below.
#
# The function accepts INTEGER n as parameter.

def staircase(n):
    const = []
    for x in range(1, n + 1):
        for y in range(n - x):
            const.append(' ')
        for z in range(x):
            const.append('#')
        for a in range(len(const)):
            print(const[a], end='')
        const = []
        print('')

if __name__ == '__main__':
    n = int(input().strip())

    staircase(n)